/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AcknowledgeScreenRecordingRequest {
    #[serde(rename = "participantJid", skip_serializing_if = "Option::is_none")]
    pub participant_jid: Option<String>,
    #[serde(rename = "roomId", skip_serializing_if = "Option::is_none")]
    pub room_id: Option<String>,
    #[serde(rename = "conversationId", skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
}

impl AcknowledgeScreenRecordingRequest {
    pub fn new() -> AcknowledgeScreenRecordingRequest {
        AcknowledgeScreenRecordingRequest {
            participant_jid: None,
            room_id: None,
            conversation_id: None,
        }
    }
}


