/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ActivityCodeReference {
    /// The globally unique identifier for the object.
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The secondary presences of this activity code.
    #[serde(rename = "secondaryPresences", skip_serializing_if = "Option::is_none")]
    pub secondary_presences: Option<Vec<crate::models::SecondaryPresence>>,
    /// The URI for this object
    #[serde(rename = "selfUri", skip_serializing_if = "Option::is_none")]
    pub self_uri: Option<String>,
}

impl ActivityCodeReference {
    pub fn new(id: String) -> ActivityCodeReference {
        ActivityCodeReference {
            id,
            name: None,
            secondary_presences: None,
            self_uri: None,
        }
    }
}


