/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */

/// AdherenceSettings : Schedule Adherence Configuration



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AdherenceSettings {
    /// The threshold in minutes where an alert will be triggered when an agent is considered severely out of adherence
    #[serde(rename = "severeAlertThresholdMinutes", skip_serializing_if = "Option::is_none")]
    pub severe_alert_threshold_minutes: Option<i32>,
    /// Target adherence percentage
    #[serde(rename = "adherenceTargetPercent", skip_serializing_if = "Option::is_none")]
    pub adherence_target_percent: Option<i32>,
    /// The threshold in seconds for which agents should not be penalized for being momentarily out of adherence
    #[serde(rename = "adherenceExceptionThresholdSeconds", skip_serializing_if = "Option::is_none")]
    pub adherence_exception_threshold_seconds: Option<i32>,
    /// Whether to treat all non-on-queue activities as equivalent for adherence purposes
    #[serde(rename = "nonOnQueueActivitiesEquivalent", skip_serializing_if = "Option::is_none")]
    pub non_on_queue_activities_equivalent: Option<bool>,
    /// Whether to track on-queue activities
    #[serde(rename = "trackOnQueueActivity", skip_serializing_if = "Option::is_none")]
    pub track_on_queue_activity: Option<bool>,
    #[serde(rename = "ignoredActivityCategories", skip_serializing_if = "Option::is_none")]
    pub ignored_activity_categories: Option<Box<crate::models::IgnoredActivityCategories>>,
}

impl AdherenceSettings {
    /// Schedule Adherence Configuration
    pub fn new() -> AdherenceSettings {
        AdherenceSettings {
            severe_alert_threshold_minutes: None,
            adherence_target_percent: None,
            adherence_exception_threshold_seconds: None,
            non_on_queue_activities_equivalent: None,
            track_on_queue_activity: None,
            ignored_activity_categories: None,
        }
    }
}


