/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AuditFacet {
    /// The name of the field on which to facet.
    #[serde(rename = "name")]
    pub name: String,
    /// The type of the facet, DATE or STRING.
    #[serde(rename = "type")]
    pub _type: String,
}

impl AuditFacet {
    pub fn new(name: String, _type: String) -> AuditFacet {
        AuditFacet {
            name,
            _type,
        }
    }
}


