/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Biography {
    /// Personal detailed description
    #[serde(rename = "biography", skip_serializing_if = "Option::is_none")]
    pub biography: Option<String>,
    #[serde(rename = "interests", skip_serializing_if = "Option::is_none")]
    pub interests: Option<Vec<String>>,
    #[serde(rename = "hobbies", skip_serializing_if = "Option::is_none")]
    pub hobbies: Option<Vec<String>>,
    #[serde(rename = "spouse", skip_serializing_if = "Option::is_none")]
    pub spouse: Option<String>,
    /// User education details
    #[serde(rename = "education", skip_serializing_if = "Option::is_none")]
    pub education: Option<Vec<crate::models::Education>>,
}

impl Biography {
    pub fn new() -> Biography {
        Biography {
            biography: None,
            interests: None,
            hobbies: None,
            spouse: None,
            education: None,
        }
    }
}


