/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BulkShiftTradeStateUpdateRequest {
    /// The shift trades to update
    #[serde(rename = "entities")]
    pub entities: Vec<crate::models::BulkUpdateShiftTradeStateRequestItem>,
}

impl BulkShiftTradeStateUpdateRequest {
    pub fn new(entities: Vec<crate::models::BulkUpdateShiftTradeStateRequestItem>) -> BulkShiftTradeStateUpdateRequest {
        BulkShiftTradeStateUpdateRequest {
            entities,
        }
    }
}


