/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CampaignTimeSlot {
    /// The start time of the interval as an ISO-8601 string, i.e. HH:mm:ss
    #[serde(rename = "startTime")]
    pub start_time: String,
    /// The end time of the interval as an ISO-8601 string, i.e. HH:mm:ss
    #[serde(rename = "stopTime")]
    pub stop_time: String,
    /// The day of the interval. Valid values: [1-7], representing Monday through Sunday
    #[serde(rename = "day")]
    pub day: i32,
}

impl CampaignTimeSlot {
    pub fn new(start_time: String, stop_time: String, day: i32) -> CampaignTimeSlot {
        CampaignTimeSlot {
            start_time,
            stop_time,
            day,
        }
    }
}


