/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CoachingAppointmentStatusResponse {
    #[serde(rename = "appointment", skip_serializing_if = "Option::is_none")]
    pub appointment: Option<Box<crate::models::CoachingAppointmentReference>>,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<crate::models::UserReference>>,
    /// Creation time of the status. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss[.mmm]Z
    #[serde(rename = "dateCreated", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<String>,
    /// The status of the coaching appointment
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
}

impl CoachingAppointmentStatusResponse {
    pub fn new() -> CoachingAppointmentStatusResponse {
        CoachingAppointmentStatusResponse {
            appointment: None,
            created_by: None,
            date_created: None,
            status: None,
        }
    }
}

/// The status of the coaching appointment
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "Scheduled")]
    Scheduled,
    #[serde(rename = "InProgress")]
    InProgress,
    #[serde(rename = "Completed")]
    Completed,
    #[serde(rename = "InvalidSchedule")]
    InvalidSchedule,
}

impl Default for Status {
    fn default() -> Status {
        Self::Scheduled
    }
}

