/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CoachingSlotsResponse {
    /// List of slots where coaching appointment can be scheduled
    #[serde(rename = "suggestedSlots", skip_serializing_if = "Option::is_none")]
    pub suggested_slots: Option<Vec<crate::models::CoachingSlot>>,
    /// Periods of availability for attendees to schedule coaching appointment
    #[serde(rename = "attendeeSchedules", skip_serializing_if = "Option::is_none")]
    pub attendee_schedules: Option<Vec<crate::models::UserAvailableTimes>>,
    /// Periods of availability for facilitators to schedule coaching appointment
    #[serde(rename = "facilitatorSchedules", skip_serializing_if = "Option::is_none")]
    pub facilitator_schedules: Option<Vec<crate::models::UserAvailableTimes>>,
    /// Detailed data for WFM scheduled activities
    #[serde(rename = "wfmScheduleActivities", skip_serializing_if = "Option::is_none")]
    pub wfm_schedule_activities: Option<Vec<crate::models::WfmScheduleActivity>>,
}

impl CoachingSlotsResponse {
    pub fn new() -> CoachingSlotsResponse {
        CoachingSlotsResponse {
            suggested_slots: None,
            attendee_schedules: None,
            facilitator_schedules: None,
            wfm_schedule_activities: None,
        }
    }
}


