/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ColumnStatus {
    /// Indicates whether or not an individual contact method column is contactable.
    #[serde(rename = "contactable", skip_serializing_if = "Option::is_none")]
    pub contactable: Option<bool>,
}

impl ColumnStatus {
    pub fn new() -> ColumnStatus {
        ColumnStatus {
            contactable: None,
        }
    }
}


