/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConsultTransferUpdate {
    /// Determines to whom the initiating participant is speaking.
    #[serde(rename = "speakTo")]
    pub speak_to: SpeakTo,
}

impl ConsultTransferUpdate {
    pub fn new(speak_to: SpeakTo) -> ConsultTransferUpdate {
        ConsultTransferUpdate {
            speak_to,
        }
    }
}

/// Determines to whom the initiating participant is speaking.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpeakTo {
    #[serde(rename = "DESTINATION")]
    DESTINATION,
    #[serde(rename = "OBJECT")]
    OBJECT,
    #[serde(rename = "BOTH")]
    BOTH,
}

impl Default for SpeakTo {
    fn default() -> SpeakTo {
        Self::DESTINATION
    }
}

