/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ContactListFilterRange {
    /// The minimum value of the range. Required for the operator BETWEEN.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<String>,
    /// The maximum value of the range. Required for the operator BETWEEN.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
    /// Whether or not to include the minimum in the range.
    #[serde(rename = "minInclusive", skip_serializing_if = "Option::is_none")]
    pub min_inclusive: Option<bool>,
    /// Whether or not to include the maximum in the range.
    #[serde(rename = "maxInclusive", skip_serializing_if = "Option::is_none")]
    pub max_inclusive: Option<bool>,
    /// A set of values that the contact data should be in. Required for the IN operator.
    #[serde(rename = "inSet", skip_serializing_if = "Option::is_none")]
    pub in_set: Option<Vec<String>>,
}

impl ContactListFilterRange {
    pub fn new() -> ContactListFilterRange {
        ContactListFilterRange {
            min: None,
            max: None,
            min_inclusive: None,
            max_inclusive: None,
            in_set: None,
        }
    }
}


