/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationThreadingWindowSetting {
    /// The type of messenger
    #[serde(rename = "messengerType")]
    pub messenger_type: MessengerType,
    /// The conversation threading window timeout (Minutes) of specified messenger type
    #[serde(rename = "timeoutInMinutes")]
    pub timeout_in_minutes: i64,
}

impl ConversationThreadingWindowSetting {
    pub fn new(messenger_type: MessengerType, timeout_in_minutes: i64) -> ConversationThreadingWindowSetting {
        ConversationThreadingWindowSetting {
            messenger_type,
            timeout_in_minutes,
        }
    }
}

/// The type of messenger
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessengerType {
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "facebook")]
    Facebook,
    #[serde(rename = "twitter")]
    Twitter,
    #[serde(rename = "line")]
    Line,
    #[serde(rename = "whatsapp")]
    Whatsapp,
    #[serde(rename = "webmessaging")]
    Webmessaging,
    #[serde(rename = "instagram")]
    Instagram,
    #[serde(rename = "open")]
    Open,
}

impl Default for MessengerType {
    fn default() -> MessengerType {
        Self::Sms
    }
}

