/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ConversationRoutingData {
    #[serde(rename = "queue", skip_serializing_if = "Option::is_none")]
    pub queue: Option<Box<crate::models::AddressableEntityRef>>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Box<crate::models::AddressableEntityRef>>,
    /// The priority of the conversation to use for routing decisions
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// The skills to use for routing decisions
    #[serde(rename = "skills", skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<crate::models::AddressableEntityRef>>,
    /// A collection of agents and their assigned scores for this conversation (0 - 100, higher being better), for use in routing to preferred agents
    #[serde(rename = "scoredAgents", skip_serializing_if = "Option::is_none")]
    pub scored_agents: Option<Vec<crate::models::ScoredAgent>>,
}

impl ConversationRoutingData {
    pub fn new() -> ConversationRoutingData {
        ConversationRoutingData {
            queue: None,
            language: None,
            priority: None,
            skills: None,
            scored_agents: None,
        }
    }
}


