/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateCallbackResponse {
    #[serde(rename = "conversation")]
    pub conversation: Box<crate::models::DomainEntityRef>,
    /// The list of communication identifiers for the callback participants
    #[serde(rename = "callbackIdentifiers")]
    pub callback_identifiers: Vec<crate::models::CallbackIdentifier>,
}

impl CreateCallbackResponse {
    pub fn new(conversation: crate::models::DomainEntityRef, callback_identifiers: Vec<crate::models::CallbackIdentifier>) -> CreateCallbackResponse {
        CreateCallbackResponse {
            conversation: Box::new(conversation),
            callback_identifiers,
        }
    }
}


