/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateTimeOffPlanRequest {
    /// The name of this time off plan.
    #[serde(rename = "name")]
    pub name: String,
    /// The set of activity code IDs to associate with this time off plan.
    #[serde(rename = "activityCodeIds", skip_serializing_if = "Option::is_none")]
    pub activity_code_ids: Option<Vec<String>>,
    /// The set of time off limit IDs to associate with this time off plan.
    #[serde(rename = "timeOffLimitIds", skip_serializing_if = "Option::is_none")]
    pub time_off_limit_ids: Option<Vec<String>>,
    /// Auto approval rule for the time off plan.
    #[serde(rename = "autoApprovalRule")]
    pub auto_approval_rule: AutoApprovalRule,
    /// The number of days before the time off request start date for when the request will be expired from the waitlist.
    #[serde(rename = "daysBeforeStartToExpireFromWaitlist", skip_serializing_if = "Option::is_none")]
    pub days_before_start_to_expire_from_waitlist: Option<i32>,
    /// Whether this time off plan should be used by agents.
    #[serde(rename = "active")]
    pub active: bool,
}

impl CreateTimeOffPlanRequest {
    pub fn new(name: String, auto_approval_rule: AutoApprovalRule, active: bool) -> CreateTimeOffPlanRequest {
        CreateTimeOffPlanRequest {
            name,
            activity_code_ids: None,
            time_off_limit_ids: None,
            auto_approval_rule,
            days_before_start_to_expire_from_waitlist: None,
            active,
        }
    }
}

/// Auto approval rule for the time off plan.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AutoApprovalRule {
    #[serde(rename = "Never")]
    Never,
    #[serde(rename = "Always")]
    Always,
    #[serde(rename = "CheckLimits")]
    CheckLimits,
}

impl Default for AutoApprovalRule {
    fn default() -> AutoApprovalRule {
        Self::Never
    }
}

