/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomEventAttribute {
    /// The data type of the custom attribute.
    #[serde(rename = "dataType")]
    pub data_type: String,
    /// The value of the custom attribute.
    #[serde(rename = "value")]
    pub value: String,
}

impl CustomEventAttribute {
    pub fn new(data_type: String, value: String) -> CustomEventAttribute {
        CustomEventAttribute {
            data_type,
            value,
        }
    }
}


