/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataAvailabilityResponse {
    /// Date and time before which data is guaranteed to be available in the datalake. Date time is represented as an ISO-8601 string. For example: yyyy-MM-ddTHH:mm:ss[.mmm]Z
    #[serde(rename = "dataAvailabilityDate", skip_serializing_if = "Option::is_none")]
    pub data_availability_date: Option<String>,
}

impl DataAvailabilityResponse {
    pub fn new() -> DataAvailabilityResponse {
        DataAvailabilityResponse {
            data_availability_date: None,
        }
    }
}


