/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */

/// IdleEventTrigger : Details about an idle event trigger



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdleEventTrigger {
    /// Name of event triggered after period of inactivity.
    #[serde(rename = "eventName")]
    pub event_name: String,
    /// Number of seconds of inactivity before an event is triggered.
    #[serde(rename = "idleAfterSeconds", skip_serializing_if = "Option::is_none")]
    pub idle_after_seconds: Option<i64>,
}

impl IdleEventTrigger {
    /// Details about an idle event trigger
    pub fn new(event_name: String) -> IdleEventTrigger {
        IdleEventTrigger {
            event_name,
            idle_after_seconds: None,
        }
    }
}


