/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InboundDomainPatchRequest {
    #[serde(rename = "mailFromSettings", skip_serializing_if = "Option::is_none")]
    pub mail_from_settings: Option<Box<crate::models::MailFromResult>>,
    #[serde(rename = "customSMTPServer", skip_serializing_if = "Option::is_none")]
    pub custom_smtp_server: Option<Box<crate::models::DomainEntityRef>>,
}

impl InboundDomainPatchRequest {
    pub fn new() -> InboundDomainPatchRequest {
        InboundDomainPatchRequest {
            mail_from_settings: None,
            custom_smtp_server: None,
        }
    }
}


