/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ItemValidationLimits {
    #[serde(rename = "minLength")]
    pub min_length: Box<crate::models::MinLength>,
    #[serde(rename = "maxLength")]
    pub max_length: Box<crate::models::MaxLength>,
}

impl ItemValidationLimits {
    pub fn new(min_length: crate::models::MinLength, max_length: crate::models::MaxLength) -> ItemValidationLimits {
        ItemValidationLimits {
            min_length: Box::new(min_length),
            max_length: Box::new(max_length),
        }
    }
}


