/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyActionMap {
    /// The ID of the actionMap in the Journey System which triggered this action
    #[serde(rename = "id")]
    pub id: String,
    /// The version number of the actionMap in the Journey System at the time this action was triggered
    #[serde(rename = "version")]
    pub version: i32,
}

impl JourneyActionMap {
    pub fn new(id: String, version: i32) -> JourneyActionMap {
        JourneyActionMap {
            id,
            version,
        }
    }
}


