/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KnowledgeSearchResponse {
    /// Search Id
    #[serde(rename = "searchId", skip_serializing_if = "Option::is_none")]
    pub search_id: Option<String>,
    /// Total number of records returned
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of pages returned in the result calculated according to the pageSize and the total
    #[serde(rename = "pageCount", skip_serializing_if = "Option::is_none")]
    pub page_count: Option<i32>,
    /// Number of records according to the page size
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
    /// Current page number for the returned records
    #[serde(rename = "pageNumber", skip_serializing_if = "Option::is_none")]
    pub page_number: Option<i32>,
    /// Results associated to the search response
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<crate::models::KnowledgeSearchDocument>>,
}

impl KnowledgeSearchResponse {
    pub fn new() -> KnowledgeSearchResponse {
        KnowledgeSearchResponse {
            search_id: None,
            total: None,
            page_count: None,
            page_size: None,
            page_number: None,
            results: None,
        }
    }
}


