/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NluDetectionRequest {
    #[serde(rename = "input")]
    pub input: Box<crate::models::NluDetectionInput>,
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<crate::models::NluDetectionContext>>,
}

impl NluDetectionRequest {
    pub fn new(input: crate::models::NluDetectionInput) -> NluDetectionRequest {
        NluDetectionRequest {
            input: Box::new(input),
            context: None,
        }
    }
}


