/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NluInfo {
    #[serde(rename = "domain", skip_serializing_if = "Option::is_none")]
    pub domain: Option<Box<crate::models::AddressableEntityRef>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<crate::models::NluDomainVersion>>,
    #[serde(rename = "intents", skip_serializing_if = "Option::is_none")]
    pub intents: Option<Vec<crate::models::Intent>>,
    #[serde(rename = "engineVersion", skip_serializing_if = "Option::is_none")]
    pub engine_version: Option<String>,
}

impl NluInfo {
    pub fn new() -> NluInfo {
        NluInfo {
            domain: None,
            version: None,
            intents: None,
            engine_version: None,
        }
    }
}


