/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchUser {
    /// The globally unique identifier for the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The value that denotes if acdAutoAnswer is set on the user
    #[serde(rename = "acdAutoAnswer", skip_serializing_if = "Option::is_none")]
    pub acd_auto_answer: Option<bool>,
}

impl PatchUser {
    pub fn new() -> PatchUser {
        PatchUser {
            id: None,
            acd_auto_answer: None,
        }
    }
}


