/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PhoneNumber {
    #[serde(rename = "display", skip_serializing_if = "Option::is_none")]
    pub display: Option<String>,
    #[serde(rename = "extension", skip_serializing_if = "Option::is_none")]
    pub extension: Option<i64>,
    #[serde(rename = "acceptsSMS", skip_serializing_if = "Option::is_none")]
    pub accepts_sms: Option<bool>,
    #[serde(rename = "userInput", skip_serializing_if = "Option::is_none")]
    pub user_input: Option<String>,
    #[serde(rename = "e164", skip_serializing_if = "Option::is_none")]
    pub e164: Option<String>,
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
}

impl PhoneNumber {
    pub fn new() -> PhoneNumber {
        PhoneNumber {
            display: None,
            extension: None,
            accepts_sms: None,
            user_input: None,
            e164: None,
            country_code: None,
        }
    }
}


