/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlanningGroup {
    /// The globally unique identifier for the object.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "serviceGoalTemplate", skip_serializing_if = "Option::is_none")]
    pub service_goal_template: Option<Box<crate::models::ServiceGoalTemplateReference>>,
    /// Set of route paths associated with the planning group
    #[serde(rename = "routePaths", skip_serializing_if = "Option::is_none")]
    pub route_paths: Option<Vec<crate::models::RoutePathResponse>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::WfmVersionedEntityMetadata>>,
    /// The URI for this object
    #[serde(rename = "selfUri", skip_serializing_if = "Option::is_none")]
    pub self_uri: Option<String>,
}

impl PlanningGroup {
    pub fn new() -> PlanningGroup {
        PlanningGroup {
            id: None,
            name: None,
            service_goal_template: None,
            route_paths: None,
            metadata: None,
            self_uri: None,
        }
    }
}


