/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */

/// PublishDraftInput : Draft to be published



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublishDraftInput {
    /// The current draft version.
    #[serde(rename = "version")]
    pub version: i32,
}

impl PublishDraftInput {
    /// Draft to be published
    pub fn new(version: i32) -> PublishDraftInput {
        PublishDraftInput {
            version,
        }
    }
}


