/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PublishForm {
    /// Is this form published
    #[serde(rename = "published")]
    pub published: bool,
    /// Unique Id for this version of this form
    #[serde(rename = "id")]
    pub id: String,
}

impl PublishForm {
    pub fn new(published: bool, id: String) -> PublishForm {
        PublishForm {
            published,
            id,
        }
    }
}


