/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ReportingTurnKnowledgeDocument {
    /// The ID of the knowledge document.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The the question that was used to match against the search query.
    #[serde(rename = "question", skip_serializing_if = "Option::is_none")]
    pub question: Option<String>,
    /// The corresponding answer to the question.
    #[serde(rename = "answer", skip_serializing_if = "Option::is_none")]
    pub answer: Option<String>,
    /// The confidence score of how well the question matched the search query.
    #[serde(rename = "confidence", skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
}

impl ReportingTurnKnowledgeDocument {
    pub fn new() -> ReportingTurnKnowledgeDocument {
        ReportingTurnKnowledgeDocument {
            id: None,
            question: None,
            answer: None,
            confidence: None,
        }
    }
}


