/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoleDivision {
    /// Role to be associated with the given division which forms a grant
    #[serde(rename = "roleId")]
    pub role_id: String,
    /// Division associated with the given role which forms a grant
    #[serde(rename = "divisionId")]
    pub division_id: String,
}

impl RoleDivision {
    pub fn new(role_id: String, division_id: String) -> RoleDivision {
        RoleDivision {
            role_id,
            division_id,
        }
    }
}


