/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RoutingConversationAttributesResponse {
    /// Current priority value on in-queue conversation. Range:[-25000000, 25000000]
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    /// Current routing skills on in-queue conversation
    #[serde(rename = "skills", skip_serializing_if = "Option::is_none")]
    pub skills: Option<Vec<crate::models::RoutingSkill>>,
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<Box<crate::models::Language>>,
    /// Current scored agents on in-queue conversation
    #[serde(rename = "scoredAgents", skip_serializing_if = "Option::is_none")]
    pub scored_agents: Option<Vec<crate::models::ScoredAgent>>,
}

impl RoutingConversationAttributesResponse {
    pub fn new() -> RoutingConversationAttributesResponse {
        RoutingConversationAttributesResponse {
            priority: None,
            skills: None,
            language: None,
            scored_agents: None,
        }
    }
}


