/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SchedulingTestingOptionsRequest {
    /// Whether to enable fast scheduling
    #[serde(rename = "fastScheduling", skip_serializing_if = "Option::is_none")]
    pub fast_scheduling: Option<bool>,
    /// Whether to force delayed scheduling
    #[serde(rename = "delayScheduling", skip_serializing_if = "Option::is_none")]
    pub delay_scheduling: Option<bool>,
    /// Whether to force scheduling to fail
    #[serde(rename = "failScheduling", skip_serializing_if = "Option::is_none")]
    pub fail_scheduling: Option<bool>,
    /// Whether to populate warnings in the generated schedule
    #[serde(rename = "populateWarnings", skip_serializing_if = "Option::is_none")]
    pub populate_warnings: Option<bool>,
    /// Whether to populate deprecated warnings in the generated schedule
    #[serde(rename = "populateDeprecatedWarnings", skip_serializing_if = "Option::is_none")]
    pub populate_deprecated_warnings: Option<bool>,
}

impl SchedulingTestingOptionsRequest {
    pub fn new() -> SchedulingTestingOptionsRequest {
        SchedulingTestingOptionsRequest {
            fast_scheduling: None,
            delay_scheduling: None,
            fail_scheduling: None,
            populate_warnings: None,
            populate_deprecated_warnings: None,
        }
    }
}


