/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */

/// TextBotUserInputAlternative : User input data used in a bot flow turn.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TextBotUserInputAlternative {
    #[serde(rename = "transcript")]
    pub transcript: Box<crate::models::TextBotTranscript>,
}

impl TextBotUserInputAlternative {
    /// User input data used in a bot flow turn.
    pub fn new(transcript: crate::models::TextBotTranscript) -> TextBotUserInputAlternative {
        TextBotUserInputAlternative {
            transcript: Box::new(transcript),
        }
    }
}


