/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateWorkPlanRotationAgentRequest {
    /// The ID of an agent in this work plan rotation
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "dateRange", skip_serializing_if = "Option::is_none")]
    pub date_range: Option<Box<crate::models::DateRangeWithOptionalEnd>>,
    /// Start position of the work plan in the pattern for this agent in the work plan rotation. Position value starts from 0
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    /// If marked true for this agent when updating, then this agent will be removed from this work plan rotation
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,
}

impl UpdateWorkPlanRotationAgentRequest {
    pub fn new(user_id: String) -> UpdateWorkPlanRotationAgentRequest {
        UpdateWorkPlanRotationAgentRequest {
            user_id,
            date_range: None,
            position: None,
            delete: None,
        }
    }
}


