/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */

/// UserScheduleFullDayTimeOffMarker : Marker to indicate an approved full day time off request



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserScheduleFullDayTimeOffMarker {
    /// The date associated with the time off request that this marker corresponds to.  Date only, in ISO-8601 format.
    #[serde(rename = "managementUnitDate", skip_serializing_if = "Option::is_none")]
    pub management_unit_date: Option<String>,
    /// The id for the activity code.  Look up a map of activity codes with the activities route
    #[serde(rename = "activityCodeId", skip_serializing_if = "Option::is_none")]
    pub activity_code_id: Option<String>,
    /// Whether this is paid time off
    #[serde(rename = "isPaid", skip_serializing_if = "Option::is_none")]
    pub is_paid: Option<bool>,
    /// The length in minutes of this time off marker
    #[serde(rename = "lengthInMinutes", skip_serializing_if = "Option::is_none")]
    pub length_in_minutes: Option<i32>,
    /// The description associated with the time off request that this marker corresponds to
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// If marked true for updating an existing full day time off marker, it will be deleted
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<bool>,
}

impl UserScheduleFullDayTimeOffMarker {
    /// Marker to indicate an approved full day time off request
    pub fn new() -> UserScheduleFullDayTimeOffMarker {
        UserScheduleFullDayTimeOffMarker {
            management_unit_date: None,
            activity_code_id: None,
            is_paid: None,
            length_in_minutes: None,
            description: None,
            delete: None,
        }
    }
}


