/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserStations {
    #[serde(rename = "associatedStation", skip_serializing_if = "Option::is_none")]
    pub associated_station: Option<Box<crate::models::UserStation>>,
    #[serde(rename = "effectiveStation", skip_serializing_if = "Option::is_none")]
    pub effective_station: Option<Box<crate::models::UserStation>>,
    #[serde(rename = "defaultStation", skip_serializing_if = "Option::is_none")]
    pub default_station: Option<Box<crate::models::UserStation>>,
    #[serde(rename = "lastAssociatedStation", skip_serializing_if = "Option::is_none")]
    pub last_associated_station: Option<Box<crate::models::UserStation>>,
}

impl UserStations {
    pub fn new() -> UserStations {
        UserStations {
            associated_station: None,
            effective_station: None,
            default_station: None,
            last_associated_station: None,
        }
    }
}


