/*
 * PureCloud Platform API
 *
 * With the PureCloud Platform API, you can control all aspects of your PureCloud environment. With the APIs you can access the system configuration, manage conversations and more.
 *
 * The version of the OpenAPI document: v2
 * Contact: DeveloperEvangelists@genesys.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WebChatConfig {
    /// css class to be applied to the web chat widget.
    #[serde(rename = "webChatSkin", skip_serializing_if = "Option::is_none")]
    pub web_chat_skin: Option<WebChatSkin>,
}

impl WebChatConfig {
    pub fn new() -> WebChatConfig {
        WebChatConfig {
            web_chat_skin: None,
        }
    }
}

/// css class to be applied to the web chat widget.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebChatSkin {
    #[serde(rename = "basic")]
    Basic,
    #[serde(rename = "modern-caret-skin")]
    ModernCaretSkin,
}

impl Default for WebChatSkin {
    fn default() -> WebChatSkin {
        Self::Basic
    }
}

